### ISSUE TITLE
Cannot Install - Package Fails Integrity Check

### ISSUE THREAD

**Issue by joshuacant** [DrMerfy/vscode-overtype#40]
Hi, trying to install via the VSCode marketplace returns the following errors:

```
2023-05-15 20:05:04.998 [error] Signature: PackageIntegrityCheckFailed
    at yt.download (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)

2023-05-15 20:05:05.011 [error] PackageIntegrityCheckFailed: Signature: PackageIntegrityCheckFailed
    at yt.download (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:468)
    at async X.x (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
```

Not sure if this just a problem with my PC or something else, and figured you were the best person to know the difference. 😄

**Comment by joshuacant** [comment]
I rebooted and now it's working. Sorry for the issue spam.
